env:
  browser: true
  es2021: true

extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - "@typescript-eslint"

settings:
  import/extensions:
    - ".js"
    - ".jsx"
    - ".ts"
    - ".tsx"
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
      - ".tsx"
  import/resolver:
    node:
      extensions:
        - ".js"
        - ".jsx"
        - ".ts"
        - ".tsx"

rules:
  "no-console": 0
  "import/extensions": 0
  "no-restricted-exports": 0
  "import/prefer-default-export": 0
  "@typescript-eslint/semi":
    - "warn"
  "@typescript-eslint/no-empty-interface":
    - "error"
    - "allowSingleExtends": true

