---
root: true

plugins:
  - babel

env:
  node: true
  browser: true

parser: "@babel/eslint-parser"

extends:
  - "airbnb-base"

rules:
  no-console: 0
  import/extensions: 0
  no-unused-vars: 0
  import/prefer-default-export: 0

